export const KINDS = {
    FETCH_KINDS: 'KINDS/FETCH_KINDS',
    ADD_KIND: 'KINDS/ADD_KIND',
    ADD_KINDS_ERROR: 'KINDS/ADD_KINDS_ERROR',
    CLEAR_KINDS_ERROR: 'KINDS/CLEAR_KINDS_ERROR',
    SUCCESS: 'KINDS/SUCCESS',
};

export const USER = {
    REGISTRATION: 'USER/REGISTRATION',
    SET_AUTH: 'USER/SET_AUTH',
    SET_USER: 'USER/SET_USER',
    ADD_USER_ERROR: 'USER/ADD_USER_ERROR',
    CLEAR_USER_ERROR: 'USER/CLEAR_USER_ERROR',
};

export const APP = {
    SET_LOADING: 'USER/SET_LOADING'
};