export const TYPES = {
    FETCH_TYPES: 'TYPES/FETCH_TYPES',
    ADD_TYPE: 'TYPES/ADD_TYPE',
    ADD_TYPES_ERROR: 'TYPES/ADD_TYPES_ERROR',
    CLEAR_TYPES_ERROR: 'TYPES/CLEAR_TYPES_ERROR',
    SUCCESS: 'TYPES/SUCCESS'
};

export const USER = {
    REGISTRATION: 'USER/REGISTRATION',
    SET_AUTH: 'USER/SET_AUTH',
    SET_USER: 'USER/SET_USER',
    ADD_USER_ERROR: 'USER/ADD_USER_ERROR',
    CLEAR_USER_ERROR: 'USER/CLEAR_USER_ERROR',
};

export const APP = {
    SET_LOADING: 'USER/SET_LOADING'
};